
name: steerio-nb # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Netbeans RCP app for  https://github.com/ClickerMonkey/Steerio.git # 79 char long summary
description: |
  Steerio is a steering behavior, spatial database, and path library for games. This is a NetBeans RCP
  port of the library.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  service:
    # See 'snapcraft plugins'
    plugin: maven
    maven-options:
       -f steerio-nbp/pom.xml
